[project]
name = "hand-detect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mediapipe>=0.10.31",
    "opencv-python>=4.13.0.90",
]
